Received the following error:
Run #  python -m pytest
9
/opt/hostedtoolcache/Python/3.9.6/x64/bin/python: Error while finding module specification for 'pat_test_test.py' (ModuleNotFoundError: __path__ attribute not found on 'pat_test_test' while trying to find 'pat_test_test.py'). Try using 'pat_test_test' instead of 'pat_test_test.py' as the module name.
10
Error: Process completed with exit code 1.

Very friendly!  Thanks, trying again.